<?php

namespace Plugin\Test\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\Test\Entity\CategoryBlock;
// use Symfony\Bridge\Doctrine\RegistryInterface;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;

/**
 * CategoryBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryBlockRepository extends AbstractRepository
{
    /**
     * CategoryBlockRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, CategoryBlock::class);
    }

}
