<?php

namespace Plugin\Test\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\Test\Entity\ProductDetail;
// use Symfony\Bridge\Doctrine\RegistryInterface;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;

/**
 * ProductDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDetailRepository extends AbstractRepository
{
    /**
     * ProductDetailRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ProductDetail::class);
    }

    /**
     * @param int $id
     *
     * @return null|ProductDetail
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
